name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pause:
    runs-on: exsules-org-wide
    steps:
      - name: Sleep for 30 minutes on PRs only
        if: ${{ github.event_name == 'pull_request' }}
        run: sleep 1800
